### ISSUE TITLE
Amazing work

### ISSUE THREAD

**Issue by LJ-Zhang** [Div99/W-Stereo-Disp#2]
Thanks for your contribution to this community! 
When would you provide your pretrained weights?

**Comment by benknight135** [comment]
I am just as excited about this. I will do my best to build pre-trained models using the instructions in the repository over the next few days unless the authors beat me to it I'll post links to what I manage to generate.

**Comment by Div-Infinity** [comment]
Hi, thanks a lot for the interest in the code. I currently don't have access to the machines with the trained weights but will upload them as soon as I can get them. In the meantime, it will be great to have community-generated weights. Kudos to @benknight135

**Comment by Div-Infinity** [comment]
All the pretrained models have been added.
