### ISSUE TITLE
Missing imports

### ISSUE THREAD

**Issue by benknight135** [Div99/W-Stereo-Disp#3]
Hi,
I am trying to run the training myself using the instructions provided but there appear to be missing files. 

After downloading the SceneFlow dataset, if I try and run
```
python ./src/main_depth.py -c src/configs/sceneflow_w1.config
```
I get the following error:
```
Traceback (most recent call last):
  File "./src/main_depth.py", line 21, in <module>
    import models
  File "C:\Code\I3DR\W-Stereo-Disp\src\models\__init__.py", line 1, in <module>
    from .full_res import PSMNet as basic
ModuleNotFoundError: No module named 'models.full_res
```

Looking in this file it seems that __init__.py is actually missing a lot of the imports
```
from .full_res import PSMNet as basic
from .stackhourglass import PSMNet as stackhourglass
from .stackhourglass_classif import PSMNet as stackhourglass_classif
from .stackhourglass_edge_aware import PSMNet as stackhourglass_edge_aware
from .stackhourglass_full import PSMNet as stackhourglass_full
from .stackhourglass_semantic import PSMNet as stackhourglass_semantic
from .stackhourglass_softmax_offset import PSMNet as stackhourglass_softmax_offset
from .stackhourglass_std import PSMNet as stackhourglass_std
from .stackhourglass_volume import PSMNet as stackhourglass_volume
from .stackhourglass_volume_large_off import PSMNet as stackhourglass_volume_large_off
from .stackhourglass_volume_multihead import PSMNet as stackhourglass_multihead
from .stackhourglass_volume_semantic import PSMNet as stackhourglass_volume_semantic
from .stackhourglass_win import PSMNet as stackhourglass_win
```
Most of these are missing. Should I have done something to generate these or have they been excluded? 

I tried commenting out the missing imports and then I found an API key is required for losswise. This isn't a service I have used before but I registered for an account and added my personal API key and this let the script continue. 

This seems to work and I am currently running the training. Was this the correct procedure?

**Comment by Div-Infinity** [comment]
Hi, thanks for the interest! Yes, these files are some extra experiments that I cleaned up in the final version of the code. I will remove these imports.

Losswise is optional but is nice for visualizing the training curves, using a personal API key is the right way to go.
