### ISSUE TITLE
Question about multi-modal GT

### ISSUE THREAD

**Issue by Nicholasli1995** [Div99/W-Stereo-Disp#4]
Hi, thank you for sharing the code and I have a few questions:
1. Where can we find the generation of multi-modal ground truth (MM GT) as descripbed in the paper? 
2. Is there an implementation of Wasserstein Loss with MM GT as described by Eq. 12 in the paper?
3. Did DSGN+CDN (the best 3D AP on KITTI) use MM GT or not? I'm using DSGN and trying to reproduce DSGN+CDN+Wasserstein Loss.

**Comment by Div-Infinity** [comment]
Hi, thanks for the interest in our paper:

We haven't released the MM GT version yet but plan to do it soon.
For DSGN+CDN, we don't use MM GT as we find that that MM GT helps improve training earlier but results in similar final accuracies. 

To reproduce results for DSGN, it is easiest to compare [CDN-PSMNet](https://github.com/Div99/W-Stereo-Disp/blob/main/src/disp_models/stackhourglass_volume.py) to original [PSMNet](https://github.com/Div99/W-Stereo-Disp/blob/main/src/disp_models/stackhourglass.py) model and apply the changes to DSGN.
