### ISSUE TITLE
Question on pre-trained models

### ISSUE THREAD

**Issue by Nicholasli1995** [Div99/W-Stereo-Disp#6]
Hi, thank you for releasing the pre-trained depth models. Could you please advise if there is a script to re-produce CDN-DSGN in the current repo? Or are there instructions to do so?

**Comment by mgladkova** [comment]
Also interested!

**Comment by Div-Infinity** [comment]
Hi, it is very straightforward to modify DSGN similar to how we modify vanilla [PSMNet ](https://github.com/Div99/W-Stereo-Disp/blob/57db67d4d8ee71a47e959125f46370a8c58d5194/src/models/stackhourglass.py) to our new [version](https://github.com/Div99/W-Stereo-Disp/blob/57db67d4d8ee71a47e959125f46370a8c58d5194/src/models/stackhourglass_volume.py).

Essentially you need to directly return the cost volume output and train it with the W_loss.

**Comment by Div-Infinity** [comment]
I will try to release the CDN-DSGN code when I get time
